<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="(empty)"
	tests="1"
	failures="1"
	disabled="0"
	skipped="0"
	hostname=""
	time="0"
	timestamp="2024-10-20T00:25:18"
	>
	<testcase name="Test2" classname="Test2" time="0.0336126" status="fail">
		<failure message="Failed"/>
		<properties/>
		<system-out>Running 1 test case...
unknown location(0): [NON-XML-CHAR-0x1B][4;31;49mfatal error: in "Solver_test/solver_2_test": memory access violation at address: 0x8: no mapping at fault address[NON-XML-CHAR-0x1B][0;39;49m
/home/dima/Projects/edu/test_ci/test/test_solver_2.cpp(17): [NON-XML-CHAR-0x1B][1;36;49mlast checkpoint[NON-XML-CHAR-0x1B][0;39;49m

[NON-XML-CHAR-0x1B][1;31;49m*** 1 failure is detected in the test module "Solving_quadratic_equation"
[NON-XML-CHAR-0x1B][0;39;49m
</system-out>
	</testcase>
</testsuite>
